-- Complete Database Insert Statements
-- Generated by Pharmacy Data Pipeline
-- Date: 2025-08-07 17:54:03


-- REITZ - 2025-08-06
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'REITZ'),
    '2025-08-06',
    80353.14,
    27.34,
    22639.74,
    60160.76,
    74776.69,
    194.09,
    1.98,
    414,
    114,
    291.80053394355457,
    33265.26086956522,
    1563965.07,
    1573725.33,
    4855.66,
    55577.51,
    1515.75,
    9404.06
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- REITZ - 2025-08-01
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'REITZ'),
    '2025-08-01',
    77107.46,
    26.8,
    21595.95,
    58993.43,
    37463.65,
    203.99,
    2.06,
    378,
    150,
    287.12828985507247,
    43069.24347826087,
    1546766.46,
    1524800.69,
    436.0,
    57607.72,
    1130.5,
    9108.58
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- REITZ - 2025-08-07
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'REITZ'),
    '2025-08-07',
    35789.62,
    23.96,
    3409.85,
    10820.8,
    16616.41,
    526.32,
    5.68,
    68,
    0,
    0,
    0,
    1576838.63,
    1581516.98,
    1117.26,
    20269.67,
    2125.37,
    2527.95
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- REITZ - 2025-07-30
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'REITZ'),
    '2025-07-30',
    79800.91,
    22.13,
    17600.38,
    61917.01,
    53375.09,
    243.3,
    2.07,
    328,
    116,
    430.11776611694154,
    49893.66086956522,
    1565706.93,
    1556121.63,
    1043.37,
    48008.77,
    1176.16,
    4218.27
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- REITZ - 2025-07-31
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'REITZ'),
    '2025-07-31',
    87438.48,
    24.45,
    21380.39,
    66063.12,
    55836.39,
    247.7,
    2.37,
    353,
    121,
    426.6528206970895,
    51624.99130434783,
    1556121.63,
    1545894.9,
    0.0,
    41664.85,
    2135.35,
    21044.65
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- REITZ - 2025-08-02
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'REITZ'),
    '2025-08-02',
    39377.47,
    28.52,
    11231.88,
    28148.54,
    50937.65,
    180.63,
    2.14,
    218,
    62,
    281.3542776998598,
    17443.965217391305,
    1524800.91,
    1547590.01,
    0.0,
    29596.2,
    None,
    3804.48
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- REITZ - 2025-08-05
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'REITZ'),
    '2025-08-05',
    95437.83,
    23.81,
    22128.99,
    70794.63,
    50187.08,
    230.53,
    1.87,
    414,
    159,
    351.4764561115669,
    55884.75652173914,
    1589370.96,
    1566267.22,
    2496.18,
    52199.33,
    1839.75,
    20682.09
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- TLC WINTERTON - 2025-08-04
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'TLC WINTERTON'),
    '2025-08-04',
    68222.6,
    23.63,
    16115.28,
    52090.87,
    22572.01,
    212.53,
    1.79,
    321,
    104,
    385.26755852842814,
    40067.82608695653,
    1622999.99,
    1649511.94,
    56030.81,
    44100.0,
    None,
    14521.9
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- REITZ - 2025-08-04
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'REITZ'),
    '2025-08-04',
    89983.36,
    26.76,
    24064.62,
    65866.0,
    90583.26,
    232.52,
    1.9,
    387,
    155,
    338.7438990182328,
    52505.30434782609,
    1547705.7,
    1572365.11,
    57.84,
    55111.63,
    2779.09,
    8966.2
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- REITZ - 2025-08-03
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'REITZ'),
    '2025-08-03',
    0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    1547590.01,
    1547590.01,
    0.0,
    0,
    0,
    0
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- TLC WINTERTON - 2025-08-06
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'TLC WINTERTON'),
    '2025-08-06',
    78925.39,
    0,
    0,
    0,
    0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    39664.06,
    None,
    9413.5
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- TLC WINTERTON - 2025-08-01
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'TLC WINTERTON'),
    '2025-08-01',
    70191.87,
    0,
    0,
    0,
    0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    47969.78,
    None,
    10381.65
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- TLC WINTERTON - 2025-08-07
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'TLC WINTERTON'),
    '2025-08-07',
    29974.32,
    0,
    0,
    0,
    0,
    189.71,
    0.0,
    158,
    0,
    0,
    0,
    0,
    0,
    0,
    16988.32,
    None,
    8158.92
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- TLC WINTERTON - 2025-08-02
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'TLC WINTERTON'),
    '2025-08-02',
    28888.06,
    0,
    0,
    0,
    0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    18408.82,
    286.85,
    2103.17
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- TLC WINTERTON - 2025-08-05
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'TLC WINTERTON'),
    '2025-08-05',
    82906.29,
    0,
    0,
    0,
    0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    49552.8,
    None,
    21406.45
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- REITZ - None
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'REITZ'),
    'None',
    0,
    0,
    0,
    0,
    0,
    0.0,
    0.0,
    0,
    0,
    None,
    None,
    0,
    0,
    0,
    0,
    0,
    0
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;

