services:
  - type: web
    name: pharmacy-email-monitor
    env: python
    plan: starter
    buildCommand: pip install -r Scripts/requirements_render.txt
    startCommand: python Scripts/app_improved.py
    envVars:
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
      - key: REITZ_GMAIL_USERNAME
        fromSecret: REITZ_GMAIL_USERNAME
      - key: REITZ_GMAIL_APP_PASSWORD
        fromSecret: REITZ_GMAIL_APP_PASSWORD
      - key: PYTHON_VERSION
        value: 3.13.4 