-- Complete Database Insert Statements
-- Generated by Pharmacy Data Pipeline
-- Date: 2025-08-05 14:21:42


-- TLC WINTERTON - 2025-08-04
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'TLC WINTERTON'),
    '2025-08-04',
    68222.6,
    23.63,
    16115.28,
    52090.87,
    22572.01,
    212.53146417445484,
    1.79,
    321,
    104,
    385.26755852842814,
    40067.82608695653,
    1622999.99,
    1649511.94,
    56030.81,
    44100.0,
    None,
    14521.9
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;


-- REITZ - 2025-08-04
INSERT INTO daily_summary (
    pharmacy_id, report_date, turnover, gp_percent, gp_value, cost_of_sales, purchases,
    avg_basket_value, avg_basket_size, transactions_total, script_total, avg_script_value,
    disp_turnover, stock_opening, stock_closing, adjustments, sales_cash, sales_cod, sales_account
) VALUES (
    (SELECT id FROM pharmacies WHERE pharmacy_code = 'REITZ'),
    '2025-08-04',
    89983.36,
    26.76,
    24064.62,
    65866.0,
    90583.26,
    232.51514211886305,
    1.9,
    387,
    155,
    338.7438990182328,
    52505.30434782609,
    1561481.29,
    1586140.69,
    57.84,
    55111.63,
    2779.09,
    8966.2
) ON CONFLICT (pharmacy_id, report_date) DO UPDATE SET
    turnover = EXCLUDED.turnover,
    gp_percent = EXCLUDED.gp_percent,
    gp_value = EXCLUDED.gp_value,
    cost_of_sales = EXCLUDED.cost_of_sales,
    purchases = EXCLUDED.purchases,
    avg_basket_value = EXCLUDED.avg_basket_value,
    avg_basket_size = EXCLUDED.avg_basket_size,
    transactions_total = EXCLUDED.transactions_total,
    script_total = EXCLUDED.script_total,
    avg_script_value = EXCLUDED.avg_script_value,
    disp_turnover = EXCLUDED.disp_turnover,
    stock_opening = EXCLUDED.stock_opening,
    stock_closing = EXCLUDED.stock_closing,
    adjustments = EXCLUDED.adjustments,
    sales_cash = EXCLUDED.sales_cash,
    sales_cod = EXCLUDED.sales_cod,
    sales_account = EXCLUDED.sales_account;

