-- Top Selling Products Database Queries
-- Generated by Pharmacy Data Analysis


-- Top selling products for TLC WINTERTON
SELECT 
    sd.department_code,
    sd.stock_code,
    sd.description,
    sd.sales_qty,
    sd.sales_value,
    sd.gross_profit,
    sd.gross_profit_percent,
    p.name as pharmacy_name,
    ds.report_date
FROM sales_details sd
JOIN daily_summary ds ON sd.pharmacy_id = ds.pharmacy_id AND sd.report_date = ds.report_date
JOIN pharmacies p ON sd.pharmacy_id = p.id
WHERE p.pharmacy_code = 'TLC WINTERTON'
ORDER BY sd.sales_qty DESC
LIMIT 10;


-- Top selling products for REITZ
SELECT 
    sd.department_code,
    sd.stock_code,
    sd.description,
    sd.sales_qty,
    sd.sales_value,
    sd.gross_profit,
    sd.gross_profit_percent,
    p.name as pharmacy_name,
    ds.report_date
FROM sales_details sd
JOIN daily_summary ds ON sd.pharmacy_id = ds.pharmacy_id AND sd.report_date = ds.report_date
JOIN pharmacies p ON sd.pharmacy_id = p.id
WHERE p.pharmacy_code = 'REITZ'
ORDER BY sd.sales_qty DESC
LIMIT 10;
